# This is the function to apply the Nugget pipeline to the workload

# ----- Helper functions starts -----
# Functions here are used to help the main function

function(nugget_helper_extract_file_type FILE_NAME RESULT_VAR)
    if(FILE_NAME MATCHES ".*\\.cpp$")
        set(_type "CXX")
    elseif(FILE_NAME MATCHES ".*\\.c$")
        set(_type "C")
    elseif(FILE_NAME MATCHES ".*\\.[fF](90)?$")
        set(_type "Fortran")
    elseif(FILE_NAME MATCHES ".*\\.cu$")
        set(_type "CUDA")
    elseif(FILE_NAME MATCHES ".*\\.(h|hpp)$")
        set(_type "Header")
    elseif(FILE_NAME MATCHES ".*\\.txt$")
        set(_type "Text")
    else()
        message(FATAL_ERROR "Unknown file type: ${FILE_NAME}")
    endif()
    set(${RESULT_VAR} "${_type}" PARENT_SCOPE)
endfunction()

function(nugget_helper_dump_target_properties TARGET)
    execute_process(COMMAND ${CMAKE_COMMAND} --help-property-list
                    OUTPUT_VARIABLE _all_props)
    string(REGEX REPLACE "\n" ";" _all_props "${_all_props}")

    message(STATUS "====== Properties for target: ${TARGET} ======")
    foreach(_p ${_all_props})
        string(STRIP "${_p}" _p)
        if(_p STREQUAL "" OR _p MATCHES "<" OR _p MATCHES "LOCATION")
            continue()
        endif()
        get_target_property(_val ${TARGET} ${_p})
        if(_val AND NOT _val STREQUAL "_val-NOTFOUND")
            message(STATUS "  ${_p} = ${_val}")
        endif()
    endforeach()
    message(STATUS "====== End properties for: ${TARGET} ======")
endfunction()

function(nugget_find_target_dependencies TARGET RESULT_VAR)
    set(dependent_properties MANUALLY_ADDED_DEPENDENCIES LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
    foreach(_dep_property ${dependent_properties})
        get_target_property(_dep ${TARGET} ${_dep_property})
        if(_dep)
            list(APPEND ${RESULT_VAR} ${_dep})
        endif()
    endforeach()
    list(REMOVE_DUPLICATES ${RESULT_VAR})
    set(${RESULT_VAR} "${${RESULT_VAR}}" PARENT_SCOPE)
endfunction()

function(nugget_recursive_find_target_dependencies TARGET)
    set(_deps "")
    nugget_find_target_dependencies(${TARGET} _deps)
    nugget_helper_dump_target_properties(${TARGET})
    foreach(_dep ${_deps})
        if(TARGET ${_dep})    
            nugget_recursive_find_target_dependencies(${_dep})
        endif()
    endforeach()
endfunction()

# ----- Helper functions ends -----

# This function applies the correct compilation options to each file in the workload
function(nugget_target_file_to_IR_planning TARGET OUTPUT_TARGET) 
    # First, we need to get the source files of the target
    get_target_property(SOURCE_FILES ${TARGET} SOURCES)
    set(C_FILES "")
    set(CXX_FILES "")
    set(Fortran_FILES "")
    set(CUDA_FILES "")
    set(Header_FILES "")
    set(Text_FILES "")
    foreach(SOURCE_FILE ${SOURCE_FILES})
        # Then, we need to extract the file type and assign them into groups
        nugget_helper_extract_file_type(${SOURCE_FILE} FILE_TYPE)
        if(FILE_TYPE STREQUAL "C")
            list(APPEND C_FILES "${SOURCE_FILE}")
        elseif(FILE_TYPE STREQUAL "CXX")
            list(APPEND CXX_FILES "${SOURCE_FILE}")
        elseif(FILE_TYPE STREQUAL "Fortran")
            list(APPEND Fortran_FILES "${SOURCE_FILE}")
        elseif(FILE_TYPE STREQUAL "CUDA")
            list(APPEND CUDA_FILES "${SOURCE_FILE}")
        elseif(FILE_TYPE STREQUAL "Header")
            list(APPEND Header_FILES "${SOURCE_FILE}")
        elseif(FILE_TYPE STREQUAL "Text")
            list(APPEND Text_FILES "${SOURCE_FILE}")
        else()
            message(FATAL_ERROR "Unknown file type: ${SOURCE_FILE}")
        endif()
    endforeach(SOURCE_FILE)

    message(DEBUG "C files: ${C_FILES}")
    message(DEBUG "C++ files: ${CXX_FILES}")
    message(DEBUG "Fortran files: ${Fortran_FILES}")
    message(DEBUG "CUDA files: ${CUDA_FILES}")
    message(DEBUG "Header files: ${Header_FILES}")
    message(DEBUG "Text files: ${Text_FILES}")

    # Now, we need to apply the correct compilation options to each group
    set(C_COMPILATION_OPTIONS "")
    set(CXX_COMPILATION_OPTIONS "")
    set(Fortran_COMPILATION_OPTIONS "")
    set(CUDA_COMPILATION_OPTIONS "")

    nugget_helper_dump_target_properties(${TARGET})
    nugget_recursive_find_target_dependencies(${TARGET})

endfunction(nugget_target_file_to_IR_planning)
